name: Bug
description: File a bug/issue
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Ensure your Android device meets the requirements:
        - Android Version: 8.0 (API level 26) or higher.
        - (Verify API levels [here](https://developer.android.com/tools/releases/platforms)).

        > If issues persist, gather logs using Android Studio's LogCat. Refer to this [Video Tutorial](https://www.youtube.com/watch?v=smOzLSTaso0) for guidance.
  - type: input
    id: phone-model
    attributes:
      label: Phone Model
      description: Settings > About phone > Model (hold & copy)
      placeholder: SM-A705FN
    validations:
      required: true
  - type: input
    id: android-version
    attributes:
      label: Android Version
      description: Settings > About phone > Android version
      placeholder: Android 14
    validations:
      required: true
  - type: textarea
    id: detailed-issue-desc
    attributes:
      label: Detailed Issue Description
      placeholder: |
         - In this environment...
         - With this config...
         - Run '...'
         - See error...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
    validations:
      required: false
