name: "test"
on:
  workflow_dispatch:
  push:
    tags: [ v*.*.* ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      id: version
      uses: /
      
