name: Build Magisk/KernelSU Module

on:
  push:
    tags: [ v*.*.* ]

jobs:
  build:
    name: Build Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Apt Dependencies
        run: |
          sudo apt update -y && sudo apt upgrade -y
          sudo apt install zip unzip -y

      - name: Get module properties
        id: props
        uses: christian-draeger/read-properties@1.1.1
        with:
            path: "module.prop"
            properties: 'id version versionCode'

      - name: Build ${{ steps.read_property.props.id }}.zip
        shell: bash
        run: |
          zip -r "${{ steps.read_property.props.id }}-${{ steps.read_property.props.version }}_(${{ steps.read_property.props.versionCode }}).zip" * -x ".git" -x "README.md"
          
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
            files: "${{ steps.read_property.props.id }}-${{ steps.read_property.props.version }}_(${{ steps.read_property.props.versionCode }}).zip"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
