name: Build Magisk/KernelSU Module

on:
  push:
    tags: [ v*.*.* ]

jobs:
  build:
    name: Build Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Apt Dependencies
        run: |
          sudo apt update -y && sudo apt upgrade -y
          sudo apt install zip unzip -y

      - name: Build ${{ github.event.repository.name }}.zip
        shell: bash
        run: |
          zip -r "${{ github.event.repository.name }}.zip" * -x ".git" -x "README.md"
          
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
            files: "${{ github.event.repository.name }}.zip"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
